name: testifysms
description: "Application SMS Android avec Material Design 3."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # Package principal pour envoyer/recevoir des SMS sur Android
  telephony: ^0.2.0
  # Gestion d'état réactive
  provider: ^6.1.2
  # Formatage des dates et heures
  intl: ^0.19.0
  # Gestion des permissions système (READ_SMS, SEND_SMS, RECEIVE_SMS)
  permission_handler: ^11.3.1
  lucide_icons: ^0.257.0
  flutter_dotenv: ^6.0.0
  mobile_number: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'

flutter_native_splash:
  color: '#F9FAFB'
  image: 'assets/icon.png'
  android_12:
    image: 'assets/icon.png'
    color: '#F9FAFB'
